// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDULtyIvyVGy18k3A703foqLUPOJfaFLmo',
    appId: '1:745682564401:web:e4672cf6919728d9182c10',
    messagingSenderId: '745682564401',
    projectId: 'shartflix-bf1fc',
    authDomain: 'shartflix-bf1fc.firebaseapp.com',
    storageBucket: 'shartflix-bf1fc.firebasestorage.app',
    measurementId: 'G-ZNVJFGR8Z4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg5IPAl5_8mnkez8gREIi36JGAdB8SthU',
    appId: '1:745682564401:android:d46e75be8dbfa247182c10',
    messagingSenderId: '745682564401',
    projectId: 'shartflix-bf1fc',
    storageBucket: 'shartflix-bf1fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmL4Etflrmjtd0pCjOCs3yUpBKzWQ6lS4',
    appId: '1:745682564401:ios:75e0c71f79b9e75e182c10',
    messagingSenderId: '745682564401',
    projectId: 'shartflix-bf1fc',
    storageBucket: 'shartflix-bf1fc.firebasestorage.app',
    iosBundleId: 'com.nodelabs.shartflix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmL4Etflrmjtd0pCjOCs3yUpBKzWQ6lS4',
    appId: '1:745682564401:ios:75e0c71f79b9e75e182c10',
    messagingSenderId: '745682564401',
    projectId: 'shartflix-bf1fc',
    storageBucket: 'shartflix-bf1fc.firebasestorage.app',
    iosBundleId: 'com.nodelabs.shartflix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDULtyIvyVGy18k3A703foqLUPOJfaFLmo',
    appId: '1:745682564401:web:f2169edc447f511e182c10',
    messagingSenderId: '745682564401',
    projectId: 'shartflix-bf1fc',
    authDomain: 'shartflix-bf1fc.firebaseapp.com',
    storageBucket: 'shartflix-bf1fc.firebasestorage.app',
    measurementId: 'G-TL8XXQDWR6',
  );
}
